# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csvlinter < Formula
  desc "Streaming CSV validator with JSON-Schema support"
  homepage "https://github.com/csvlinter/csvlinter"
  version "1.8.1"

  on_macos do
    on_intel do
      url "https://github.com/csvlinter/csvlinter/releases/download/v1.8.1/csvlinter-darwin-amd64.tar.gz"
      sha256 "8611436e1f232a66cbde307c4f5a8b44857503d3069025b30398ba389aa229dd"

      def install
        bin.install "csvlinter"
      end
    end
    on_arm do
      url "https://github.com/csvlinter/csvlinter/releases/download/v1.8.1/csvlinter-darwin-arm64.tar.gz"
      sha256 "da753a2f4bcf9e4b30b3a29089230588bb967f22524a7bc1f843c9af51ced3b6"

      def install
        bin.install "csvlinter"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/csvlinter/csvlinter/releases/download/v1.8.1/csvlinter-linux-amd64.tar.gz"
        sha256 "60a292680e01cc3ad4e154ce0781487dd380b66ced74a89db4bb66a8cd817747"

        def install
          bin.install "csvlinter"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/csvlinter/csvlinter/releases/download/v1.8.1/csvlinter-linux-arm64.tar.gz"
        sha256 "e49cc7201ddac5348e896af31a7f9f55ee7e216eae3fc2034222e831a436e056"

        def install
          bin.install "csvlinter"
        end
      end
    end
  end

  test do
    (testpath/"bad.csv").write("col\nbad")
    output = shell_output("#{bin}/csvlinter bad.csv", 1)
    assert_match "Row 2", output
  end
end
